# Generated by Django 4.2.30 on 2026-05-15 21:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('platform_type', models.CharField(choices=[('android', 'Android APK'), ('mod', 'MOD APK'), ('pc', 'PC'), ('ios', 'iOS'), ('smart_tv', 'Smart TV'), ('tv_box', 'TV Box')], max_length=20, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('installation_guide', models.TextField(help_text='Enter each step on a new line, e.g. "Step 1: ..."')),
                ('features', models.TextField(help_text='One feature per line')),
                ('meta_title', models.CharField(max_length=200)),
                ('meta_description', models.CharField(max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='screenshots/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='apk.platform')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='APKVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('apk_file', models.FileField(blank=True, help_text='Upload the APK file directly (optional)', null=True, upload_to='apk/')),
                ('external_url', models.URLField(blank=True, help_text='External download link (used if no file is uploaded)')),
                ('file_size', models.CharField(help_text='e.g., 85 MB', max_length=20)),
                ('android_requirement', models.CharField(default='Android 5.0+', max_length=50)),
                ('release_date', models.DateField(default=django.utils.timezone.now)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('is_latest', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=2)),
                ('changelog', models.TextField(blank=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apk.platform')),
            ],
            options={
                'ordering': ['-release_date'],
            },
        ),
    ]
