# Generated by Django 4.2.30 on 2026-06-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(default='admin@stuntbikextreme.com', max_length=254),
        ),
    ]
