# Generated by Django 4.2.30 on 2026-06-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sitesettings_contact_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='twitter_url',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='medium_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pinterest_url',
            field=models.URLField(blank=True),
        ),
    ]
